##############################################################################
## Copyright (C) 2022-2023 Analog Devices, Inc. All rights reserved.
#
## GitHub action script for the check_for_missing_readme_md.sh script located
## in .github/scripts
##############################################################################

name: Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - 'library/**'
      - 'projects/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check for Readme.md
        run: |
          bash ./.github/scripts/check_for_missing_readme_md.sh
